# Generated by Django 5.2.6 on 2025-10-25 17:43

import volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
    ]
