# Generated by Django 5.2.6 on 2025-10-28 07:06

import volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_application_aadhar_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='aadhar_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='aadhar_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='aadhar_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='aadhar_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='affidavit',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
    ]
