# Generated by Django 5.2.6 on 2025-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_application_level_hindi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='can_view_volunteer_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name_hindi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
