# Generated by Django 5.2.6 on 2025-11-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_volunteer_can_view_volunteer_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name_hindi',
            new_name='hindi_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='level_hindi_value',
        ),
    ]
