# Generated by Django 5.2.6 on 2025-10-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyapari', '0002_alter_category_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('global', 'Global'), ('district', 'District'), ('market', 'Market'), ('state', 'State'), ('category', 'Category'), ('subcategory', 'SubCategory')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='advertisement_images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('vyapari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='vyapari.vyapari')),
            ],
        ),
    ]
