# Generated by Django 5.2.6 on 2025-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_field_worker',
            field=models.BooleanField(default=False),
        ),
    ]
