# Generated by Django 5.2.6 on 2025-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_field_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
