# Generated by Django 5.2.6 on 2025-10-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gateway_payment_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_signature_id',
        ),
    ]
